CREATE TABLE [dbo].[WorkLog]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[UserId] INT NOT NULL,
	[Working] TINYINT NOT NULL,
	[CreatedAt] DATETIME DEFAULT GETDATE(),
	FOREIGN KEY (UserId) REFERENCES [User](Id),
)
